org: puttirinki
app: puttirinki-api
service: puttirinki-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: lib/prod.handler
    events:
      - http: ANY /
