org: puttirinki
app: puttirinki-api
service: puttirinki-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: lib/prod.handler
    environment: 
      MONGO_URI: ${ssm:/mongo-uri} 
      MONGO_PASS: ${ssm:/mongo-pass~true} 
      MONGO_UNAME: ${ssm:/mongo-uname~true} 
    events:
      - http: ANY /
